deployment:
  tasks:
    - export DEPLOYPATH=/home/egomalli/public_html
    - rsync -av --exclude='.git' --exclude='node_modules' ./ $DEPLOYPATH
    - cd $DEPLOYPATH
    - if [ ! -d vendor ]; then /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --prefer-dist; fi
    - if [ ! -f $DEPLOYPATH/.env ]; then cp $DEPLOYPATH/.env.example $DEPLOYPATH/.env; fi
    - php artisan key:generate --force
    - php artisan migrate --force
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

  post-deploy:
    - cd $DEPLOYPATH
    - php artisan queue:restart
